### ISSUE TITLE
Mount packaging error, mounts should not all have fog

### ISSUE THREAD

**Issue by xielinbo85** [Suprcode/mir-eternal#108]

**Comment by periko92** [comment]
Dear ,. thanks for your issue.

Please, could you supply mount Ids, what mounts have FOG and what no?

Thanks

**Comment by xielinbo85** [comment]
![QQ截图20220907125011](https://user-images.githubusercontent.com/30097203/188817492-76ac8914-bbea-419b-90d0-bd9901732143.jpg)

**Comment by periko92** [comment]
Just the white horse doesn't have FOG ?

**Comment by xielinbo85** [comment]
There's some left

**Comment by xielinbo85** [comment]
![QQ截图20220907193530](https://user-images.githubusercontent.com/30097203/188869647-69d2b803-aaa4-4359-b682-8abd645c233f.jpg)
![QQ截图20220907193641](https://user-images.githubusercontent.com/30097203/188869681-d298fdd3-050f-47bc-ba7a-34a3d023e79d.jpg)
![QQ截图20220907193337](https://user-images.githubusercontent.com/30097203/188869713-62292fce-2148-497e-a6c1-ae5dc5a5ffce.jpg)
![QQ图片20220907193319](https://user-images.githubusercontent.com/30097203/188869735-e14b1bd1-67d1-4d41-ad16-92987ee0b5ad.png)

**Comment by xielinbo85** [comment]
![QQ截图20220907194811](https://user-images.githubusercontent.com/30097203/188871390-8fdfba3e-6f7d-4b34-83c4-7544cc56c81a.jpg)

**Comment by q1036027150** [comment]
每个不同的坐骑，都会有一个不同的效果。现在的坐骑特效是“白泽”的特效。

**Comment by bernatvadell** [comment]
fixed
