### ISSUE TITLE
Mount Issue

### ISSUE THREAD

**Issue by TrapMusicLab** [Suprcode/mir-eternal#109]
There is a problem with The Mount, Player A CAN NOT see Player B ride the mount! like the pic below.
![`2)XOWZD ZGM7 0BGWKG7IO](https://user-images.githubusercontent.com/110651151/188848265-fc183c8c-c9fb-4c18-9fa7-a8299b3ccb90.png)

**Comment by bernatvadell** [comment]
fixed
