### ISSUE TITLE
Skill Inscription

### ISSUE THREAD

**Issue by ZEWoool** [Suprcode/mir-eternal#111]
This bug is reported by the Chinese
Video:
https://www.bilibili.com/video/BV1Vg411k7DE?spm_id_from=333.337.search-card.all.click&vd_source=54ee71d0b988028cc266294beac7a65a

I don't understand how this system works and i tried to get them to explain what is happening but the translation is not great.

"二蛋。7 18:41:11
All glyph skills can card unlimited skills

二蛋。7 18:41:43
The current solution is to add a skill switch to each glyph skill"

I think inscriptions are working for skills that it should not be.

**Comment by bernatvadell** [comment]
Fixed in the last commit by @xiaozhu0232

**Comment by xiaozhu0232** [comment]
I can't solve it now, I heard that there is such a bug in the official
