### ISSUE TITLE
Mounts problem

### ISSUE THREAD

**Issue by xielinbo85** [Suprcode/mir-eternal#117]
Mounts should not only be visible to users with mounts and riding skills, but should also be visible to users without mounts，
![20220911100305](https://user-images.githubusercontent.com/30097203/189508875-1738fe7b-0b5c-44a9-8a99-4cbb18c03e8e.png)

**Comment by bernatvadell** [comment]
![image](https://user-images.githubusercontent.com/17298604/189550407-f755f805-d8c2-46aa-9997-ff4d26a7cc8e.png)

In the last version is fixed
