### ISSUE TITLE
Quest Gold Disappear

### ISSUE THREAD

**Issue by ZEWoool** [Suprcode/mir-eternal#120]
When you hand in the quest it takes 1000 Gold, you need to relog to get it back.
https://vimeo.com/748501357

**Comment by bernatvadell** [comment]
do you have the latest version of the server? it is supposed to be fixed on commit:

https://github.com/Suprcode/mir-eternal/commit/d3d12df32bbd50a8957e5ba7e3dd9622ebaa0d08
