### ISSUE TITLE
Maybe we need a telegram group to talking about the Game! 

### ISSUE THREAD

**Issue by jiuzhouhan996** [Suprcode/mir-eternal#124]
Every develop programmer thanks for your sharing.
Im a Chinese player, there are so many players like me, and we get a lot of bug for the Game, that we cant fix it.
Maybe we need create a group by any contributors in the telegram.
That can be Improve communication efficiency, we will be tell the bug to you.
At the same time you can receive the bug at the first time!

plz create a telegram group, and posted in the Issues area!
@bernatvadell

**Comment by periko92** [comment]
You all can post all issues on github, that's the purpose of this page, if we make a Telegram group or something, i'm sure it's going to get collapsed with tons of messages, just make issues and we will start reviewing them.

Thanks for your interest.
