### ISSUE TITLE
If you use the public property of Nancang, you will be disconnected

### ISSUE THREAD

**Issue by 926cs** [Suprcode/mir-eternal#127]
If you use the public property of Nancang, you will be disconnected
![image](https://user-images.githubusercontent.com/89799105/189578285-b72216cd-29d4-4387-9cdd-d642b3a48e97.png)
![image](https://user-images.githubusercontent.com/89799105/189578302-dd6e21cf-ae48-4299-8961-d4ec774726eb.png)

**Comment by periko92** [comment]
Please use latest version as this scroll has been fixed on commit #[77f7a7c]
