### ISSUE TITLE
The mentoring function cannot be used, and the application causes the server to crash!

### ISSUE THREAD

**Issue by xiaozhu0232** [Suprcode/mir-eternal#130]
The mentoring function cannot be used, and the application causes the server to crash!
![image](https://user-images.githubusercontent.com/12591216/189602813-a01767bf-45bf-468b-9986-7b4a81aaaeb4.png)
![image](https://user-images.githubusercontent.com/12591216/189602939-5fa208b9-284c-43a3-9b0f-7c00eacaca46.png)
![image](https://user-images.githubusercontent.com/12591216/189602985-f13b82bf-b2b2-42c5-a552-4895160b6fb9.png)
Does the mentoring function code need to be refactored?
![image](https://user-images.githubusercontent.com/12591216/189603091-f260aca5-bd11-415f-8433-07af5d481c85.png)

**Comment by bernatvadell** [comment]
The problem to be at the time of saving the data.

Can you explain me how to configure the teacher system? To be able to try.

**Comment by xiaozhu0232** [comment]
Mentoring is a modular function of the game
![image](https://user-images.githubusercontent.com/12591216/189639037-b32b9360-07dd-4d5a-89a4-4632fcd7ee0d.png)

**Comment by xiaozhu0232** [comment]
There are too many bugs, and I can't repair them. My heart is tired!
