### ISSUE TITLE
Client Freezing....

### ISSUE THREAD

**Issue by Johnyl1** [Suprcode/mir-eternal#138]
I get no error , but the client just freezes, this happened 2x now!!
![image](https://user-images.githubusercontent.com/63940002/189939962-241cbb65-119a-4bff-89d6-78b20e7f7dd7.png)

and i can't close it!! I have to CTRL+Alt+Del
![image](https://user-images.githubusercontent.com/63940002/189940323-d8c143f4-39c6-4313-825d-df42566d0d36.png)

**Comment by periko92** [comment]
Client it's not our work, so if you got freeze, it's your side with the client.
