### ISSUE TITLE
Quest can't be finished!

### ISSUE THREAD

**Issue by Johnyl1** [Suprcode/mir-eternal#139]
Can't finish this quest, also seems that there's 2 npc's there!
![image](https://user-images.githubusercontent.com/63940002/189945549-2af4fa66-4786-444e-819f-ab12013f3ca1.png)

**Comment by xielinbo85** [comment]
Database/System/Npc/Guards/6685-PiaoShiBa.txt  Revise  6685-扑十八.txt     Name   Revise  扑十八
