### ISSUE TITLE
The whole model does not take effect. At present, there is only the peaceful model. Unable to PK

### ISSUE THREAD

**Issue by xiaozhu0232** [Suprcode/mir-eternal#140]
The whole model does not take effect. At present, there is only the peaceful model. Unable to PK

**Comment by periko92** [comment]
Fixed on #[9527135](https://github.com/Suprcode/mir-eternal/commit/9527135b1755e518862ca98f95e60bd34b84f0e5)

**Comment by itzdd9527** [comment]
not solved
