### ISSUE TITLE
Transmission operators, the current version found two quests unusable, quests and achievements are not rewarded after completion.

### ISSUE THREAD

**Issue by 7521468** [Suprcode/mir-eternal#142]
![BB587BB3-125F-4D1B-82BC-5A84BF290EC4](https://user-images.githubusercontent.com/112101165/190036539-882f9db8-be80-4372-9dac-03a64bc3a7a0.jpeg)
![CA8CA34C-5459-4EEB-8BE0-5361BCB9F326](https://user-images.githubusercontent.com/112101165/190036558-de3ea6d8-631c-4196-86ff-08a816d6e9da.jpeg)
![DA5264F3-4786-42AF-8970-866C7EF10E00](https://user-images.githubusercontent.com/112101165/190036561-295c67a9-6a1f-43c0-b88b-5af1ab902f25.jpeg)

**Comment by 7521468** [comment]
> ![BB587BB3-125F-4D1B-82BC-5A84BF290EC4](https://user-images.githubusercontent.com/112101165/190036539-882f9db8-be80-4372-9dac-03a64bc3a7a0.jpeg) ![CA8CA34C-5459-4EEB-8BE0-5361BCB9F326](https://user-images.githubusercontent.com/112101165/190036558-de3ea6d8-631c-4196-86ff-08a816d6e9da.jpeg) ![DA5264F3-4786-42AF-8970-866C7EF10E00](https://user-images.githubusercontent.com/112101165/190036561-295c67a9-6a1f-43c0-b88b-5af1ab902f25.jpeg)

@bernatvadell

**Comment by periko92** [comment]
fixed #[9527135](https://github.com/Suprcode/mir-eternal/commit/9527135b1755e518862ca98f95e60bd34b84f0e5)
