### ISSUE TITLE
The latest update, the initial task cannot receive the task

### ISSUE THREAD

**Issue by xiaozhu0232** [Suprcode/mir-eternal#148]
The latest update, the initial task cannot receive the task！
![image](https://user-images.githubusercontent.com/12591216/190930469-f534c91d-d82f-48f0-8a16-a909088f7d43.png)

**Comment by xiaozhu0232** [comment]
Can't finish previous tasks
![image](https://user-images.githubusercontent.com/12591216/190930629-6e4c79c9-64d8-470b-a879-4715d3ca9c9f.png)

**Comment by 7521468** [comment]
你好！那个任务 传送符能用吗？有几个任务不能传送好像没有被修复，传送符 功能在源码里修改？
