### ISSUE TITLE
This task cannot be completed

### ISSUE THREAD

**Issue by Julyme** [Suprcode/mir-eternal#152]
This task cannot be completed
![微信图片_20220920090416](https://user-images.githubusercontent.com/9777901/191145084-05e45bb7-9f37-40ba-8711-45fe97736b77.jpg)

**Comment by periko92** [comment]
Can you supply Quest ID number, or name in English?
Thanks

**Comment by Julyme** [comment]
The task name may be Inscription Transmutation

**Comment by periko92** [comment]
1505 , 1506 or 1509 ?

**Comment by periko92** [comment]
fix #[c1cae06](https://github.com/Suprcode/mir-eternal/commit/c1cae06d30b097c00b90277d4c7a2844b0c45821)
