### ISSUE TITLE
Quest 

### ISSUE THREAD

**Issue by Johnyl1** [Suprcode/mir-eternal#154]
Can't finish quest!
![image](https://user-images.githubusercontent.com/63940002/191279799-b3eef691-0f55-4528-a3c0-05457a695f91.png)

![image](https://user-images.githubusercontent.com/63940002/191279907-2833d3a0-639e-4208-8d7f-fe6db5cd5129.png)

After last Update doesn't work either!!
![image](https://user-images.githubusercontent.com/63940002/191289448-ff3eac7f-9bbb-48c8-a6c7-5335f2ef62e6.png)

![image](https://user-images.githubusercontent.com/63940002/191289543-0d61486c-33db-4156-876a-19009331191c.png)

![image](https://user-images.githubusercontent.com/63940002/191289617-547e72cb-cbc1-44d9-b90a-f7081ef32c1b.png)

**Comment by periko92** [comment]
Did you try to add an inscription to the weapon? quest seems fine, i think u just need to inscript the weapon then go back to the NPC to finish quest.

**Comment by Johnyl1** [comment]
![image](https://user-images.githubusercontent.com/63940002/191374737-c103f9de-47c8-4363-9618-74d3424289d8.png)

yes its done and doesnt lemme finish it!

**Comment by periko92** [comment]
"Missions": [
    {
      "Type": "RefineInscription"
    }
  ],
  
  You need to add inscription on weapon :/ quest it's ok
