### ISSUE TITLE
Can you add a command to obtain the coordinates of the current player standing in the game coordinate conversion server

### ISSUE THREAD

**Issue by 926cs** [Suprcode/mir-eternal#163]
Can you add a command to obtain the coordinates of the current player standing in the game coordinate conversion server

**Comment by bernatvadell** [comment]
Added command: `@position`

change: https://github.com/Suprcode/mir-eternal/commit/d8b5db4cd322b1bad658ba23b20403ccf62882af

![image](https://user-images.githubusercontent.com/17298604/191904939-6b5fedea-b306-4a46-98da-2675d1f85e4b.png)
