### ISSUE TITLE
Magics disapear from belt

### ISSUE THREAD

**Issue by Johnyl1** [Suprcode/mir-eternal#25]
Magics disapear from belt , u have to put the same magic on another slot and them move it to the slot where it was!!!

**Comment by bernatvadell** [comment]
Could you pass me the SkillId of the magic you are trying to put on your belt?

**Comment by Johnyl1** [comment]
So far the Wizz and tao skills they all disapear from the belt!

**Comment by bernatvadell** [comment]
Fixed!
