### ISSUE TITLE
No bag slots and lost all items from my body!!

### ISSUE THREAD

**Issue by Johnyl1** [Suprcode/mir-eternal#33]
Updated last db and gameserver and  there's no bag slots , they are all locked to buy!! And u can buy them yes! 

And when u buy slots from the main bag it costs no money, if u buy slots from second bag it will credit money instead of removing the money from you!

Also the storage has no slots available, u need to buy them!!!

**Comment by bernatvadell** [comment]
Its normal, i changed structure of character, u need a create another char or delete User/Data.db
