### ISSUE TITLE
Server gets unresponsive and doesnt save data

### ISSUE THREAD

**Issue by Johnyl1** [Suprcode/mir-eternal#34]
Server get unresponsive most of times and we have to force close. When we force close it doesnt save data!!

**Comment by bernatvadell** [comment]
do u have a last version published?

**Comment by KingdomMir2** [comment]
yes we do

**Comment by Johnyl1** [comment]
Yep

**Comment by bernatvadell** [comment]
Data loss should not be more than 10 minutes. It is the period in which it is saved automatically.
