### ISSUE TITLE
Potions that result in disconnect

### ISSUE THREAD

**Issue by ZEWoool** [Suprcode/mir-eternal#35]
There a lot more but i assume they are all related.

705-体力强效神水
物理地址:[00:d8:61:37:07:b6]
错误提示:Exception has been thrown by the target of an invocation.

706-魔力强效神水
物理地址:[00:d8:61:37:07:b6]
错误提示:Exception has been thrown by the target of an invocation.

707-刺术神水 
物理地址:[00:d8:61:37:07:b6]
错误提示:Exception has been thrown by the target of an invocation.

708-弓术神水
物理地址:[00:d8:61:37:07:b6]
错误提示:Exception has been thrown by the target of an invocation.

712-魔力圣水
物理地址:[00:d8:61:37:07:b6]
错误提示:Exception has been thrown by the target of an invocation.

713-精神圣水
物理地址:[00:d8:61:37:07:b6]
错误提示:Exception has been thrown by the target of an invocation.

714-极速圣水
物理地址:[00:d8:61:37:07:b6]
错误提示:Exception has been thrown by the target of an invocation.

717-隐身圣水
物理地址:[00:d8:61:37:07:b6]
错误提示:Exception has been thrown by the target of an invocation.

718-疗伤圣水
物理地址:[00:d8:61:37:07:b6]
错误提示:Exception has been thrown by the target of an invocation.

**Comment by bernatvadell** [comment]
The issue has been fixed, however, it is necessary to adjust the items in the db to indicate the amount of HP and MP to recover.

I've looked at the original source code, and it's not implemented. So I don't know what values it should have.

Props example:

```json
  "Props": {
    "UsageType": 0,
    "RecoveryTime": 1,
    "RecoveryBase": 20,
    "RecoverySteps": 4
  },
```
