### ISSUE TITLE
Zuma Temple - Gameserver unresponsive

### ISSUE THREAD

**Issue by ZEWoool** [Suprcode/mir-eternal#36]
About 10 seconds in here and your gameserver becomes unresponsive, i think but not 100% sure is it's the moths inside causing it.

Edit: Seems to be happening in a lot of caves, but only happens in Bug cave when your near the elite so i assume it's monster releated.

**Comment by bernatvadell** [comment]
Does it still happen with the latest version?

**Comment by ZEWoool** [comment]
Nope, I been in multiple caves to see if this still happens and it seems good so far.
