### ISSUE TITLE
Magics and melle still fail (wizard)

### ISSUE THREAD

**Issue by Johnyl1** [Suprcode/mir-eternal#37]
attacks are still bugged, after a wile the char stops attacking with both melle and magics!! Wizard so far, tao didn't had any problem so far!!!

**Comment by periko92** [comment]
Did you try to remove Data.db after updating GameServer ? As we know on the forum you like to play it, but at the moment it's on alpha stage, and it's needed to remove all previous characters/data before use new files generated.
