### ISSUE TITLE
Server Unresponsive after hunting in Wooma temple

### ISSUE THREAD

**Issue by Johnyl1** [Suprcode/mir-eternal#38]
Usualy happens when i browse the tabs of the gameserver, now it happens just for hunting on WT.

**Comment by Johnyl1** [comment]
Hunting in WT makes server crash when to many mobs are in screen!!!

**Comment by Johnyl1** [comment]
![image](https://user-images.githubusercontent.com/63940002/181933775-8b488548-95dd-4c3a-a921-f2b435fa2d7a.png)

KK thought it was coz we were hunting in WT but no, its crashes randomly!!!

**Comment by bernatvadell** [comment]
With the latest version, does it still happen to you?
