### ISSUE TITLE
Server Gets disconected when killing Giant Caterpillars on death valley

### ISSUE THREAD

**Issue by Johnyl1** [Suprcode/mir-eternal#39]
Hunting on death vally killed 2 giant catterpillars and server disconected by itself!!!
Also the GC are dropping massevely, all of them have massive drops!!!
Doesn't start anymore!!!
![image](https://user-images.githubusercontent.com/63940002/181934816-bd8be0a5-be3e-42e2-aca3-292cce395201.png)

**Comment by bernatvadell** [comment]
Can you provide us with more information?

The exact location of where it appears
monsterid

Ty

**Comment by Johnyl1** [comment]
Didn't happen again so i think its fixed!!
