### ISSUE TITLE
Level Difference Broke

### ISSUE THREAD

**Issue by ZEWoool** [Suprcode/mir-eternal#42]
No longer works, getting max exp from any monster.

**Comment by bernatvadell** [comment]
Can you give us more information about the problem?

**Comment by ZEWoool** [comment]
Exp is suppose to decrease once you surpass the monsters level and eventually receive no exp once your high enough. I think it was 10 levels above the monster then you would receive no exp but not 100% sure on that.
But even at lvl45 i still  get max exp from Sheep.
