### ISSUE TITLE
Server doesnt load!

### ISSUE THREAD

**Issue by Johnyl1** [Suprcode/mir-eternal#46]
![image](https://user-images.githubusercontent.com/63940002/183455854-5dc6f8c4-9f62-4149-8a25-da67ae77cc70.png)

Stops there on WAN server

My Local test server Stops at the very beguining with the latest Build
![image](https://user-images.githubusercontent.com/63940002/183470429-3b417ea7-63c5-481e-9219-4d93ae89b6b8.png)

**Comment by Johnyl1** [comment]
Ok this is weird, if i use the exe's from the workflow it works, but if i compile the exe myself it doesnt pass the loading data!!!

**Comment by bernatvadell** [comment]
I have fixed several important bugs in the last commit.
