### ISSUE TITLE
Server still doesnt boot

### ISSUE THREAD

**Issue by Johnyl1** [Suprcode/mir-eternal#47]
![image](https://user-images.githubusercontent.com/63940002/183474511-29bc3912-640f-478c-a571-3978cc235196.png)

On debug i get this!!! And yes im using latest release!!!

**Comment by bernatvadell** [comment]
please inspect value for files[i].FullName, that error gives why you don't have the updated database.

**Comment by bernatvadell** [comment]
I have seen in the logs that it referred to mob 1011, I have noticed that in the github database it is updated correctly.

![image](https://user-images.githubusercontent.com/17298604/183480572-3de68f28-8ab7-4c17-b135-0603f8b04e4d.png)

Database\System\Npc\Monsters\1011-蜈蚣.txt

**Comment by Johnyl1** [comment]
Well mine is like urs, and im downloading everything from github when u guys release!! and still nothing, there's more ppl i know with that problem!!!

**Comment by bernatvadell** [comment]
and are you copying the database to the bin/gameserver folder?
