### ISSUE TITLE
Taoist skill summon skele doesnt work

### ISSUE THREAD

**Issue by Johnyl1** [Suprcode/mir-eternal#52]
Can´t summon the skele!

**Comment by periko92** [comment]
thanks johnyl1 for your review, i've tested this, and Summon Beast is not working also,

We'll review the code for any errors on mobs.

**Comment by Johnyl1** [comment]
Really help's the tao, Xena help's on debug so she really needs that book working!

**Comment by Johnyl1** [comment]
KK SummonShinsu doesnt work either, and probn the rest of the summons wont work, i cant test coz the server crashed for the 17th time and im gonna w8 till it gets fixed and playable to try again! lol

**Comment by periko92** [comment]
We try our best johnyl. Hope you understand

Obtener Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
