### ISSUE TITLE
New crash this time in the mines!!

### ISSUE THREAD

**Issue by Johnyl1** [Suprcode/mir-eternal#54]
![image](https://user-images.githubusercontent.com/63940002/184264930-38633f8d-26ce-499a-af6a-870922fb4c6b.png)

![image](https://user-images.githubusercontent.com/63940002/184265168-f324130e-c20f-43fe-8d9b-d2748ebda95e.png)

System.AccessViolationException
  HResult=0x80004003
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

i think the error is the same, the difference is that was on a dedicated dual xeon server with 128 gb ram!! I was just runing away from a few mobs when happened, this time was in the mines!!!

Drop rate was at 1.0

**Comment by periko92** [comment]
Error for me appears to be in "debug tab" where server -> client packets are show,

ElAmO when he got spare time will have a look on it

**Comment by periko92** [comment]
Dear Johny, 
thanks for your review.

Is your code located at: MainForm.cs between lines 278-300 like this?
![image](https://user-images.githubusercontent.com/109764547/184455675-dc1b0acf-cb30-4136-b92c-09c83d1fa93a.png)

Waiting your answer,
Regards

**Comment by periko92** [comment]
Dear johny,

Can you tell us what version of client r you using ?

**Comment by Johnyl1** [comment]
Im using the lates from the chinese client i think! i updated with the patch....
![image](https://user-images.githubusercontent.com/63940002/184493301-05183458-4900-4635-8dd7-47630a31b472.png)

**Comment by periko92** [comment]
Dear, you have to use the 1.0.3.59 (184549) to avoid crash with new packets from last update on client. As last update its not implemented on GS

Obtener Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Johnyl1** [comment]
Yeah didn't know... lol saw on lomcn!!
