### ISSUE TITLE
Delete Anouncement crashes server!!

### ISSUE THREAD

**Issue by Johnyl1** [Suprcode/mir-eternal#55]
![image](https://user-images.githubusercontent.com/63940002/184493935-22433cbc-ce12-4b46-937d-e327e4067ee5.png)

![image](https://user-images.githubusercontent.com/63940002/184493969-50c5b8db-0902-41a7-ab59-6f2023ae01b5.png)

**Comment by bernatvadell** [comment]
fixed!
