### ISSUE TITLE
Zuma temple Disconects ppl from server

### ISSUE THREAD

**Issue by Johnyl1** [Suprcode/mir-eternal#56]
We entered ZT got a few mobs around us and we got disconected, couldnt connect again, and when i restarted the debug the USER db was corrupt!!! No error on the VS debug window at all!

Now when i start server with same DB gives this error on server window!
![image](https://user-images.githubusercontent.com/63940002/184503145-4320f616-efbd-4450-8b8d-76a10cd126a7.png)
Even deleteing the User dir the error continues and doesn't let anyone pass the gates!!!

and here's the VS debug!!
![image](https://user-images.githubusercontent.com/63940002/184503512-ff095a70-d33c-4e25-96ba-6d408b1e49ac.png)

After cleaning up, i start debug with the backup user db and it passes the gates but gives this error on loading to the game.

![image](https://user-images.githubusercontent.com/63940002/184503897-ad4e7b29-176f-404b-933c-f12b1a6da3ba.png)

**Comment by periko92** [comment]
Thanks johnyl1 for your review.
That fanplayer it's the same error as yesterday you posted.

Please, **make sure you remove FULL DATABASE FOLDER BEFORE START SERVER.** and force a fetch from the github.
If you modify drops, items or anything inside database folder, server will crash..
