### ISSUE TITLE
Zuma Temple disconecting ppl!

### ISSUE THREAD

**Issue by Johnyl1** [Suprcode/mir-eternal#57]
We were killing a zuma, got this
![image](https://user-images.githubusercontent.com/63940002/184518743-d4682b42-97da-433e-95b3-680c437c3a17.png)

There's no error on the debug window, but when i try to run the server again i get this!

![image](https://user-images.githubusercontent.com/63940002/184518789-461627a2-96b0-4326-b43c-3fc15a61acb9.png)

Server doesnt run anymore and i have to reset all stuff to be able to login again!

**Comment by Johnyl1** [comment]
KK wanted to test on local server alone to check if it happens again, it did, didn't crash as fast as the online server, took like 20 mins hunting, gather some WedgeMoths and killed a few Zumas then when i was killing this one it happened! no error on screen as u can see, but i get disconected, server is responsive but it stoped by itself.

![image](https://user-images.githubusercontent.com/63940002/184534478-0596863b-8c65-4753-8937-f711d6b69afc.png)

You can see the START server button is green  to start the server. This also happened after i gave myself a few things, you can see on the Window was 裁决之杖 and a 嗜魂法杖.

![image](https://user-images.githubusercontent.com/63940002/184534565-204398c2-8c73-4e27-9fa4-34c9d3f06827.png)

Now if i start the degug for the server again here it is again! It doesnt start at all.

![image](https://user-images.githubusercontent.com/63940002/184534678-208db4b7-159a-4d75-91b6-12fd81a98dab.png)


Sorry for posting so many stuff, but i really wanna help here!

**Comment by Johnyl1** [comment]
Another crash, this time was as soon i hit that BBM....

![image](https://user-images.githubusercontent.com/63940002/184558865-9d576f37-76db-468c-a3fb-fdbf084ccfa8.png)

**Comment by Johnyl1** [comment]
KK AHHHHHHHHH, found the problem of ZT, it's the BBM's, when they start spawning the small maggots the server crashes!!!!

**Comment by periko92** [comment]
we will have a look on it.
