### ISSUE TITLE
Warning MSB3243 Unable to resolve conflict between 'System.Design, Version=6.0.2.0, Culture=neutral, 

### ISSUE THREAD

**Issue by teddyvgt** [Suprcode/mir-eternal#58]
![image](https://user-images.githubusercontent.com/3284347/184531833-9fd4faf8-76fa-40a6-a577-026786c9b6d5.png)
Warning MSB3243 Unable to resolve conflict between 'System.Design, Version=6.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Design'. "System.Design, Version=6.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" is being randomly selected. Launcher E:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets 2302

**Comment by periko92** [comment]
Dear, thanks for your review, you need to reasign the assemblies again, should be a conflict now, please make a new pull and add it into references.

**Comment by periko92** [comment]
@teddyvgt finally did you fixed it? if so please close issue
