### ISSUE TITLE
ADD new announcement and Start Announcement crash server

### ISSUE THREAD

**Issue by Johnyl1** [Suprcode/mir-eternal#60]
Add announcement crash!
![image](https://user-images.githubusercontent.com/63940002/184628143-2aa14029-0ac4-4cec-a4b1-3be70a22a720.png)

Start Announcement crash!
![image](https://user-images.githubusercontent.com/63940002/184628187-eb336bcc-467d-4b6f-bd2a-7cd94efefa1e.png)

**Comment by periko92** [comment]
You already reported this, please, don't clone bugs as we're looking into it.

**Comment by Johnyl1** [comment]
sorry, sisnce i posted that was the delete announces , i didn't thougt u would read again! lol anyway good work...
