### ISSUE TITLE
Tao magics problem!

### ISSUE THREAD

**Issue by Johnyl1** [Suprcode/mir-eternal#62]
They stop working, u press the key and nothing happens!! So far only Tao fails!

**Comment by Johnyl1** [comment]
So far it happened with healing and soul fireballl

**Comment by periko92** [comment]
do you have last update for database... ? skills are fixed and are all now working.. like always, check your files @Johnyl1

**Comment by Johnyl1** [comment]
I have the final version….

**Comment by periko92** [comment]
did you force update database? got tao pets working now? as far i know after update i've been playing with tao, and all skills were working fine
![image](https://user-images.githubusercontent.com/109764547/185238773-0d6a0ccb-0b27-4daf-b83f-7b6dbda34b27.png)

**Comment by Johnyl1** [comment]
Well might have to update again, i just noticed that there was an update wile i was working, but that bug doesnt always happen… but its annoying lol
