### ISSUE TITLE
Tips Mall not found

### ISSUE THREAD

**Issue by xiaozhu0232** [Suprcode/mir-eternal#66]
Tips Mall not found
![image](https://user-images.githubusercontent.com/12591216/185630594-70bdb4dd-9992-46ac-bcdb-4399ca5aa556.png)
![image](https://user-images.githubusercontent.com/12591216/185630561-f05dd57d-5dee-4ed6-8fa7-4db8916a618d.png)

**Comment by periko92** [comment]
Describe a bit more that bug/error, so we can have a look on it, no sense info

**Comment by xiaozhu0232** [comment]
> Describe a bit more that bug/error, so we can have a look on it, no sense info

please help me!!!

**Comment by bernatvadell** [comment]
upgrade your client to the last version with official launcher.
