### ISSUE TITLE
The upper left corner of the achievement task to receive the server crash, the log reports an error, the wrong packet

### ISSUE THREAD

**Issue by xiaozhu0232** [Suprcode/mir-eternal#67]
The upper left corner of the achievement task to receive the server crash, the log reports an error, the wrong packet
![image](https://user-images.githubusercontent.com/12591216/185627541-f09495cd-e570-4d86-9f57-743a2f101791.png)
Receive award  
![image](https://user-images.githubusercontent.com/12591216/185627640-eaf68a4a-084f-49c2-951c-1b4c5651b588.png)
game disconnect

**Comment by periko92** [comment]
do you have any picture of the error ? or the element that make the crash? please, try to debug server in VS or attach any screenshot relevant
