### ISSUE TITLE
Shinsu doesnt do damage!

### ISSUE THREAD

**Issue by Johnyl1** [Suprcode/mir-eternal#68]
Shinsu doesn't do any damage!!! 0 hit to a scarecrow or anyother mob!

**Comment by periko92** [comment]
Dear johnyl1,

Shinsu works like a charm, i mean, there's no errors and it attacks.

![image](https://user-images.githubusercontent.com/109764547/185558456-75582311-d9db-49bf-aba9-16a576f547ad.png)

**Comment by periko92** [comment]
![image](https://user-images.githubusercontent.com/109764547/185558820-7f46f78f-fe3c-4d6d-ab38-a22f377d3e11.png)

**Comment by Johnyl1** [comment]
Can u post a pic of the client version u use?

**Comment by periko92** [comment]
Dear Johnyl1, Im using 2 versions, 1.0.3.62 and 1.0.3.63 (184947) and it's working very well.

I mean, if shinsu has a problem is not on CLIENT SIDE, it should be SERVER SIDE, and at this moment, there's no problem with the shinsu, so  your problem its on your side like most of the time.

Please check you have all latest files .....

**Comment by Johnyl1** [comment]
Where did u get the client coz when i update it gives me 
![image](https://user-images.githubusercontent.com/63940002/185594804-236a3c7b-7887-470b-a32d-70f6c2099697.png)
