### ISSUE TITLE
Use a random stone once, and it will send a few extra. BUG

### ISSUE THREAD

**Issue by xiaozhu0232** [Suprcode/mir-eternal#70]
Use a random stone once, and it will send a few extra. BUG

![image](https://user-images.githubusercontent.com/12591216/185629641-a53ce21b-48f0-4074-a7b7-5caa66717afc.png)
![image](https://user-images.githubusercontent.com/12591216/185629797-cbd7af29-b5c4-46e7-83c5-9f16bca69808.png)
![image](https://user-images.githubusercontent.com/12591216/185630310-8bf0ba0e-dce4-4288-9406-ea8ae92c771f.png)

**Comment by bernatvadell** [comment]
Please, can you send me a name item?

**Comment by xiaozhu0232** [comment]
> 拜托，你能给我发一个名字吗？
random teleportation stone   3 kinds of stones in the mall are the same
![image](https://user-images.githubusercontent.com/12591216/185634372-d9aad36e-dfd0-40dd-b9b0-c1f955ba73cc.png)

**Comment by xiaozhu0232** [comment]
![image](https://user-images.githubusercontent.com/12591216/185644881-16ba8b21-a5d5-46ba-b56d-eb855fcf7969.png)
