### ISSUE TITLE
Char stops walking and do magics

### ISSUE THREAD

**Issue by Johnyl1** [Suprcode/mir-eternal#73]
Doesn't happen much but sometimes the char freezes and stops making magigs and walking! So far hapened with my wizz!

**Comment by bernatvadell** [comment]
It is possible that it is due to some translation of some skill, we would need to know a little more, such as what skills you have used before before getting blocked.

**Comment by Johnyl1** [comment]
Using thunderbolt

**Comment by periko92** [comment]
Dear johnyl1, did you have more problems with that skill?

Because i've been using it a lot, and no fail at all, the only thing i noticed it's the MP recovery it's very high now.
![image](https://user-images.githubusercontent.com/109764547/185932763-f20b2d9f-1058-44a3-b254-78fbdbed5da8.png)

**Comment by Johnyl1** [comment]
Well its been ok now, but like u said, some caves the mp recovery is so fast that i dont use mp pots, but its weird coz i was on ST hunting and the mp wasnt lowering, then i went to town ang got back and it normal again... weird.

**Comment by periko92** [comment]
we will have a look at mana regen on wizards, thanks.
