### ISSUE TITLE
TrapHexagon pssoble issue!

### ISSUE THREAD

**Issue by Johnyl1** [Suprcode/mir-eternal#74]
![image](https://user-images.githubusercontent.com/63940002/186044512-61e79bd9-9a44-4635-bf09-1880efa99363.png)

Xena has it lvled at max but doesnt trap anything!!

![image](https://user-images.githubusercontent.com/63940002/186044569-23a15073-74d7-4275-8026-9b4e68a70a75.png)

**Comment by periko92** [comment]
fixed on last commit
![image](https://user-images.githubusercontent.com/109764547/187045860-5785c8f3-55d2-480f-93ef-553ef3610771.png)

**Comment by periko92** [comment]
![image](https://user-images.githubusercontent.com/109764547/187045881-2cfdb0de-a398-40e9-882c-de70cd7933ab.png)
