### ISSUE TITLE
Provides a video of the progress bar in MOUNTING and dismounting skills and a picture of the progress bar in opening a treasure chest

### ISSUE THREAD

**Issue by 7521468** [Suprcode/mir-eternal#85]
![43B4191B-4508-43E3-A374-D26FCDAC2CA9](https://user-images.githubusercontent.com/112101165/186809591-acc15607-6138-4d0d-963d-8624507470b8.jpeg)

https://user-images.githubusercontent.com/112101165/186809600-1ed51ed4-6150-42ed-b80a-825107088876.MOV

**Comment by bernatvadell** [comment]
Woa! Ty!

**Comment by bernatvadell** [comment]
Hi @7521468 

Can you provide packets captured with tool published at lomcn during mount & dismount?

https://www.lomcn.org/forum/threads/sniffer-packets-app.109074/

**Comment by 7521468** [comment]
> 嗨@7521468
> 
> 您能提供在lomcn上安装和卸载期间发布的工具捕获的数据包吗？
> 
> https://www.lomcn.org/forum/threads/sniffer-packets-app.109074/



> 嗨@7521468
> 
> 您能提供工具捕获的数据包吗？
> 
> https://www.lomcn.org/forum/threads/sniffer-packets-app.109074/



> Hi @7521468
> 
> Can you provide packets captured with tool published at lomcn during mount & dismount?
> 
> https://www.lomcn.org/forum/threads/sniffer-packets-app.109074/

I'm sorry I can't provide it now. I have a tool to capture data packets, but I don't have such a game to provide data packets. I will try my best in the past two days to see if I can get data packets.

**Comment by bernatvadell** [comment]
Thank you!

**Comment by bernatvadell** [comment]
Added progress bar on open chest, for the mount, we need packets :(

**Comment by 7521468** [comment]
> Added progress bar on open chest, for the mount, we need packets :(

I found a game that can extract data packets, but the tool in my hand can't be used, and I get an error when I open it. I don't know why. Could you please send that tool to me? Let me try, that download tool website I can not log on, thank you!

**Comment by 7521468** [comment]
@bernatvadell I made the data package you want, and also attached the video (after riding a horse, press the horse riding skill, a progress bar will automatically appear and automatically mount the horse, this is a bug)
[Mounting skills (including dismounting) progress bar data package.zip](https://github.com/Suprcode/mir-eternal/files/9443872/Mounting.skills.including.dismounting.progress.bar.data.package.zip)

https://user-images.githubusercontent.com/112101165/187185485-098e2ac3-36e5-4106-a5f4-07d636eceb56.MP4


https://user-images.githubusercontent.com/112101165/187185510-93b90d9c-7f52-4c60-ae2a-e90b278692b2.MP4

[The mount progress bar includes the automatic mount bug video of dismounting.zip](https://github.com/Suprcode/mir-eternal/files/9443960/The.mount.progress.bar.includes.the.automatic.mount.bug.video.of.dismounting.zip)

**Comment by bernatvadell** [comment]
Thanks a lot! Now we only need the packets. Please check the link below for a step-by-step guide to getting the information.

https://www.lomcn.org/forum/threads/sniffer-packets-app.109074/

Thank you!!!

**Comment by 7521468** [comment]
> 非常感谢！ 现在我们只需要数据包。 请查看以下链接以获取获取信息的分步指南。
> 
> [https://www.lomcn.org/forum/threads/sniffer-packets-app.109074/ ](https://www.lomcn.org/forum/threads/sniffer-packets-app.109074/)
> 
> 谢谢！！！

@bernatvadell I have uploaded the data package, you can take a look at the ZIP format of the decompressed package. Unzip the zip file on top of the video. . brother! !

**Comment by bernatvadell** [comment]
![image](https://user-images.githubusercontent.com/17298604/187200326-85e0cc29-cf01-4f31-b66a-99852d3090e0.png)

We need a packets with raw file.

NOTE: The first link not work. In the second, im see two videos

**Comment by 7521468** [comment]
> ![image](https://user-images.githubusercontent.com/17298604/187200326-85e0cc29-cf01-4f31-b66a-99852d3090e0.png)
> 
> We need a packets with raw file.
> 
> NOTE: The first link not work. In the second, im see two videos

[Two packets captured.zip](https://github.com/Suprcode/mir-eternal/files/9444567/Two.packets.captured.zip)
@bernatvadell re-uploaded

**Comment by bernatvadell** [comment]
Oh yeah brother!

**Comment by 7521468** [comment]
> Oh yeah brother!

@bernatvadell Game SERVER AND ACCOUNT SERVER COMPILED INTO EXE WILL PRODUCE a lot OF USELESS FOLDERS AND USELESS files, can you optimize, the useless files IN THE COMPILED do not produce

**Comment by bernatvadell** [comment]
In a compilation it is normal that hundreds of files are generated, but when you do the publish, we have the "Single FIle" option enabled that generates a single optimized file in Release.

![image](https://user-images.githubusercontent.com/17298604/187362870-bd89f997-13da-487f-9687-b606eb494627.png)

![image](https://user-images.githubusercontent.com/17298604/187363016-1b49c190-5dad-4507-ba2a-0943e7142dfa.png)

![image](https://user-images.githubusercontent.com/17298604/187363098-336f1d7e-4e67-445f-99b3-ec74eb089c33.png)

![image](https://user-images.githubusercontent.com/17298604/187363152-24dc1cc7-544d-4bbb-878e-65f3b61f599e.png)

**Comment by 7521468** [comment]
> In a compilation it is normal that hundreds of files are generated, but when you do the publish, we have the "Single FIle" option enabled that generates a single optimized file in Release.
> 
> ![image](https://user-images.githubusercontent.com/17298604/187362870-bd89f997-13da-487f-9687-b606eb494627.png)
> 
> ![image](https://user-images.githubusercontent.com/17298604/187363016-1b49c190-5dad-4507-ba2a-0943e7142dfa.png)
> 
> ![image](https://user-images.githubusercontent.com/17298604/187363098-336f1d7e-4e67-445f-99b3-ec74eb089c33.png)
> 
> ![image](https://user-images.githubusercontent.com/17298604/187363152-24dc1cc7-544d-4bbb-878e-65f3b61f599e.png)

@

> In a compilation it is normal that hundreds of files are generated, but when you do the publish, we have the "Single FIle" option enabled that generates a single optimized file in Release.
> 
> ![image](https://user-images.githubusercontent.com/17298604/187362870-bd89f997-13da-487f-9687-b606eb494627.png)
> 
> ![image](https://user-images.githubusercontent.com/17298604/187363016-1b49c190-5dad-4507-ba2a-0943e7142dfa.png)
> 
> ![image](https://user-images.githubusercontent.com/17298604/187363098-336f1d7e-4e67-445f-99b3-ec74eb089c33.png)
> 
> ![image](https://user-images.githubusercontent.com/17298604/187363152-24dc1cc7-544d-4bbb-878e-65f3b61f599e.png)

@bernatvadell Oh yeah, thank you so much, man! Is the data package I sent you yesterday working? I did my best!

**Comment by bernatvadell** [comment]
Of course! im analyzing packets! Thank you!

**Comment by 7521468** [comment]
Hello! Sorry to bother you again! Can YOU ADD a button TO DISABLE BOWman, DRAGONLANCE, and ASSASSIN CHARACTER CREATION in THE GAME SERVER LAUNCHER Settings? This MEANS THAT THE THREE CLASSES WILL NOT BE SHOWN WHEN THE CHARACTERS ARE CREATED WHEN CLOSED, which means that they can not be seen directly, but can be created and seen when opened! (ONLY SHOWS STAY, MANA, Tao) When turned ON the other side, it now shows SIX classes. &nbsp;&nbsp;I'm sorry that I can only send email to disturb you because of poor Internet!

发自我的iPhone


------------------ Original ------------------
From: Bernat Vadell ***@***.***&gt;
Date: Wed,Aug 31,2022 0:09 AM
To: Suprcode/mir-eternal ***@***.***&gt;
Cc: 7521468 ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [Suprcode/mir-eternal] Provides a video of the progress bar inMOUNTING and dismounting skills and a picture of the progress bar in opening atreasure chest (Issue #85)





 
Of course! im analyzing packets! Thank you!

**Comment by 7521468** [comment]
> Of course! im analyzing packets! Thank you!

@bernatvadell Hello! Sorry to bother you again! Can YOU ADD a button TO DISABLE BOWman, DRAGONLANCE, and ASSASSIN CHARACTER CREATION in THE GAME SERVER LAUNCHER Settings? This MEANS THAT THE THREE CLASSES WILL NOT BE SHOWN WHEN THE CHARACTERS ARE CREATED WHEN CLOSED, which means that they can not be seen directly, but can be created and seen when opened! (ONLY SHOWS STAY, MANA, Tao) When turned ON the other side, it now shows SIX classes.

**Comment by 7521468** [comment]
![1E0EDB93-250A-405C-8E76-8575D8552195](https://user-images.githubusercontent.com/112101165/187705894-39aa856e-1ca6-4c88-86a9-65416d16550f.png)

**Comment by bernatvadell** [comment]
Hi @7521468 can you send me packets from selection scene? (please open new issue)
