### ISSUE TITLE
Ingot bag (small), there are hints, but no items.

### ISSUE THREAD

**Issue by xiaozhu0232** [Suprcode/mir-eternal#87]
Ingot bag (small), there are hints, but no items.
![image](https://user-images.githubusercontent.com/12591216/187038282-22b7ba79-03ae-4107-a6af-fe948f95f3b2.png)
GM command sent neither
![image](https://user-images.githubusercontent.com/12591216/187038341-eba7f369-8d55-4757-9fc3-d053b4c4f177.png)

Friends server, normal items

![1_4PR`_PU 1N9ULNTIFY75O](https://user-images.githubusercontent.com/12591216/187038397-e0f79c6f-839c-426e-9dce-302b70b4e002.png)
![1_4PR`_PU 1N9ULNTIFY75O](https://user-images.githubusercontent.com/12591216/187038402-9d8c18f5-19d9-4735-8d2b-159130dd8e42.png)

**Comment by periko92** [comment]
Dear, we have checked and item ID on gameserver doesn't match actual client update, it showing different item, we'll have a look into it, thanks
