### ISSUE TITLE
chinese repair

### ISSUE THREAD

**Issue by cangsanglong** [Suprcode/mir-eternal#90]
This is the content of Chinese repair

https://wwc.lanzouy.com/i5qX00agzu7e

**Comment by xiaozhu0232** [comment]
不完善的！
Imperfect, many not repaired

**Comment by cangsanglong** [comment]
imperfect

**Comment by bernatvadell** [comment]
What repaired?

**Comment by cangsanglong** [comment]
This is a Chinese repair skill, monster....

**Comment by Powersongpower** [comment]
> 这是中文维修的内容
> 
> https://wwc.lanzouy.com/i5qX00agzu7e

我测试了，会出现崩溃，某个BOSS释放技能的时候
错误信息:
未将对象引用设置到对象的实例。
堆栈信息:
   在 游戏服务器.模板类.技能实例.处理任务()
   在 游戏服务器.模板类.技能实例.处理任务()
   在 游戏服务器.模板类.技能实例.处理任务()
   在 游戏服务器.地图类.怪物实例.处理对象数据()
   在 游戏服务器.地图类.地图处理网关.处理数据()
   在 游戏服务器.主程.服务循环()

**Comment by periko92** [comment]
> This is a Chinese repair skill, monster....

dear, if you can make a pull, we can update it :)
