### ISSUE TITLE
Why doesn't my package work?

### ISSUE THREAD

**Issue by xiaozhu0232** [Suprcode/mir-eternal#91]
Why doesn't my package work?
![image](https://user-images.githubusercontent.com/12591216/187478692-164a8d83-b190-4297-947b-937c66a94106.png)
![image](https://user-images.githubusercontent.com/12591216/187478814-0a528ed6-e464-40e8-a2e8-d98c8be7948a.png)

**Comment by bernatvadell** [comment]
https://dotnet.microsoft.com/en-us/download/dotnet/6.0

![image](https://user-images.githubusercontent.com/17298604/187487922-2c31e960-b861-4c4d-9b7f-cf185c974138.png)
