### ISSUE TITLE
Char still stops walking and do magics!

### ISSUE THREAD

**Issue by Johnyl1** [Suprcode/mir-eternal#92]
Well it's still there, was on ZT after the mazes and i had those freezes, it stops doing thunderbolt and stops walking!!!

**Comment by periko92** [comment]
> Well it's still there, was on ZT after the mazes and i had those freezes, it stops doing thunderbolt and stops walking!!!

maybe did you get paralyzed by wedgemoths ?

**Comment by Johnyl1** [comment]
Nop, no wedgemoths around!

**Comment by periko92** [comment]
dear, if you can't bring more info, we can't find a solution, i've been playing 2 hours with a wiz on ZT and no crash, no stop walking, ....

**Comment by Johnyl1** [comment]
Well it happend once in after the maze... but ill try to check it again

**Comment by periko92** [comment]
without info we can't do a research.

**Comment by cangsanglong** [comment]
Because the skill has a cooldown time

**Comment by periko92** [comment]
I'm going to review the cooldown of Thunderbolt.

Thanks for the tip.
