### ISSUE TITLE
Where are the gold coins and props initially sent?

### ISSUE THREAD

**Issue by xiaozhu0232** [Suprcode/mir-eternal#95]
Where are the gold coins and props initially sent?
![image](https://user-images.githubusercontent.com/12591216/188196673-1c74ac10-df5d-4ba8-86d6-dbe7917522d9.png)

**Comment by bernatvadell** [comment]
by the moment gold is hardcoded

![image](https://user-images.githubusercontent.com/17298604/188197168-725f9baa-c4ff-4492-a9be-a9cfffc446f2.png)

And you can edit starter items in database folder: 
\\System\\Items\\Inscription\\
![image](https://user-images.githubusercontent.com/17298604/188197385-a520e924-40e2-4ec3-bdc5-ac819a07f835.png)
