### ISSUE TITLE
Using the Inscription skill, the game crashes

### ISSUE THREAD

**Issue by xiaozhu0232** [Suprcode/mir-eternal#97]
Using the Inscription skill, the game crashes
 "SkillName": "基本剑术-3-幽速印",
  "SkillId": 1031,
   狮子吼凌月印 = 10372,

![R ~)9 6}ROT@D$B@P0J6_GD](https://user-images.githubusercontent.com/12591216/188271758-5061fab5-1d7e-42f2-ae53-7a314380ae6f.png)
![NF{`5PNB$2M$NBF_ZA0XKJN](https://user-images.githubusercontent.com/12591216/188271775-cd8d7264-fff5-4aac-a8e7-3051f151f45a.png)
![AU6Y6RZI2Z5 CNPG`K2VPJ1](https://user-images.githubusercontent.com/12591216/188271780-05c14db0-9be5-47f9-b7d0-de8c70263501.png)
![U)AJOL HEA4IDZDJ_Y)KY](https://user-images.githubusercontent.com/12591216/188271782-23c8fc2b-5ac5-4c35-9bb0-9b91aefe1301.png)
![)XKZB1N87~PX0BXSZNW$FGD](https://user-images.githubusercontent.com/12591216/188271785-b9e80b35-f2cd-40d6-a2ac-f8171bbb4825.png)

**Comment by xiaozhu0232** [comment]
Using the Inscription skill, the game crashes
"SkillName": "基本剑术-3-幽速印",
"SkillId": 1031,

**Comment by xiaozhu0232** [comment]
![image](https://user-images.githubusercontent.com/12591216/188682694-5fbe8c3c-b825-4d17-a144-9994df396295.png)
log:
Error message:
The given key '0' was not present in the dictionary.
Stack information:
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at GameServer.Templates.SkillInstance.Process() in E:\CQYH\GameServer\Templates\SkillInstance.cs:line 590
   at GameServer.Maps.PlayerObject.Process() in E:\CQYH\GameServer\Maps\PlayerObject.cs:line 968
   at GameServer.Maps.MapGatewayProcess.Process() in E:\CQYH\GameServer\Maps\MapGatewayProcess.cs:line 618
   at GameServer.MainProcess.MainLoop() in E:\CQYH\GameServer\MainProcess.cs:line 87
https://user-images.githubusercontent.com/12591216/188271785-b9e80b35-f2cd-40d6-a2ac-f8171bbb4825.png

**Comment by bernatvadell** [comment]
thanks to @xiaozhu0232
