### ISSUE TITLE
Skill BUG ，Unlimited CD Unlimited Use

### ISSUE THREAD

**Issue by xiaozhu0232** [Suprcode/mir-eternal#98]
Unlimited CD Unlimited Use

https://drive.google.com/file/d/10WOU2wXYBOGgHb0XTM6fX_3VJd3hYQ89/view?usp=sharing
https://drive.google.com/file/d/1FNAyjvyxWv9vnItbYCDRJitWeEK3MeBN/view?usp=sharing

https://www.bilibili.com/video/BV1Vg411k7DE?spm_id_from=333.337.search-card.all.click&vd_source=54ee71d0b988028cc266294beac7a65a

**Comment by periko92** [comment]
[https://youtu.be/Phu-z9eqxFY](url)

i don't see any problem

**Comment by xiaozhu0232** [comment]
Follow the tutorial to learn the card bug 
https://www.bilibili.com/video/BV1Vg411k7DE?spm_id_from=333.337.search-card.all.click&vd_source=54ee71d0b988028cc266294beac7a65a

**Comment by MirSoul** [comment]
It seems to be in F12, and check the skill of automatic cultivation,
Drag the icon dropped in the shortcut bar, and you can 0cd when you go online again?

**Comment by xiaozhu0232** [comment]
Still the previous method, quit the game, still can BUG

**Comment by q1036027150** [comment]
我上次发的解决方式，都能解决。

**Comment by xiaozhu0232** [comment]
加Q吗？

**Comment by q1036027150** [comment]
可

**Comment by xiaozhu0232** [comment]
QQ多少啊

**Comment by q1036027150** [comment]
你的给我

**Comment by xiaozhu0232** [comment]
536457822

**Comment by q1036027150** [comment]
群

**Comment by xiaozhu0232** [comment]
我的QQ啊！加不了吗？

**Comment by q1036027150** [comment]
嗯

**Comment by xiaozhu0232** [comment]
在搜下，应该可以了!

**Comment by q1036027150** [comment]
找不到

**Comment by xiaozhu0232** [comment]
你Q多少啊！或者群也可啊！

**Comment by q1036027150** [comment]
138541496

**Comment by periko92** [comment]
Do you know how to fix this? Remember this is to post issues or fixes...

**Comment by q1036027150** [comment]
我之前发过了

**Comment by bernatvadell** [comment]
I'm trying to reproduce the error following the tutorial, but I can't. Is it necessary to use the inscription skill to reproduce it?
