### ISSUE TITLE
- Mounts should not have a progress bar. There are bugs unlocking resource packs in packages

### ISSUE THREAD

**Issue by 7521468** [Suprcode/mir-eternal#99]
@bernatvadell hi! I PROVIDED THE MOUNT DATA PACKAGE, YOU did a GREAT JOB, BUT THERE SHOULD BE NO PROGRESS BAR ON THE DOWN MOUNT, I hope you will CANCEL THE PROGRESS bar ON THE DOWN MOUNT. There is a resource pack in the package. It is not necessary to unlock all resource packs with gold coins after the package is online. I hope you can check it and fix it.

**Comment by 7521468** [comment]
> @bernatvadell hi! I PROVIDED THE MOUNT DATA PACKAGE, YOU did a GREAT JOB, BUT THERE SHOULD BE NO PROGRESS BAR ON THE DOWN MOUNT, I hope you will CANCEL THE PROGRESS bar ON THE DOWN MOUNT. There is a resource pack in the package. It is not necessary to unlock all resource packs with gold coins after the package is online. I hope you can check it and fix it.

Dismount should not have a progress bar

**Comment by periko92** [comment]
On official there's a cooldown to dismount the horse

**Comment by 7521468** [comment]
> On official there's a cooldown to dismount the horse

What I provided is not official, you just don't believe it. Originally, two packets were given to you, one is a progress bar for mounting and the other is a bug for dismounting. Dismounting has a cooldown CD but no progress bar

**Comment by bernatvadell** [comment]
So in the official server, he gets off the mount instantly?

**Comment by 7521468** [comment]
> So in the official server, he gets off the mount instantly?
Yes!

**Comment by bernatvadell** [comment]
fixed
